### ISSUE TITLE
Zig build is broken

### ISSUE THREAD

**Issue by dmorn** [ggerganov/ggml#617]
I did a bisect, and the first bad commit is 3e551c0bda2a1c47f88f178fa3a79ea2c80d15ed. I'll check later if I can fix it, in the meanwhile I'm opening the issue for reference.

**Comment by dmorn** [comment]
Some files are missing in the build
```
diff --git a/build.zig b/build.zig
index 5aa379d..b6c98e7 100644
--- a/build.zig
+++ b/build.zig
@@ -37,6 +37,7 @@ pub fn build(b: *std.build.Builder) void {
     lib.addIncludePath(.{ .path = "./include/ggml" });
     lib.addCSourceFiles(&.{
         "src/ggml.c",
+        "src/ggml-alloc.c",
     }, &.{"-std=c11"});
     lib.linkLibC();
     lib.linkLibCpp();
```

I'll see if I can do something for the main branch as this one is from Aug.

**Comment by dmorn** [comment]
OK so basically for master it is needed to add the .c files in src, that's it. Now the compiler is erroring with
```
error: cannot compare strings with !=
pub inline fn GGML_UNREACHABLE() @TypeOf(GGML_ASSERT(!("statement should not be reached" != 0))) {
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
tests/test0.zig:2:11: error: C import failed: AnalysisFail
const c = @cImport({
          ^~~~~~~~
referenced by:
    main: tests/test0.zig:13:18
```

Same for every other zig test.
